/*
 * Copyright (c) Forge Development LLC
 * SPDX-License-Identifier: LGPL-2.1-only
 */
package net.minecraftforge.renamer.gradle;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import javax.inject.Inject;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.RegularFile;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.MapProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.compile.JavaCompile;
import org.gradle.process.CommandLineArgumentProvider;

abstract class MixinSourceSetConfigImpl implements MixinSourceSetConfig {
	private static final Logger LOGGER = LogManager.getLogger(MixinConfig.class);
	private final RenamerExtensionImpl ext;
	private final MixinSourceSetConfig config;
	final SourceSet sourceSet;

	@Inject
	public MixinSourceSetConfigImpl(RenamerExtensionImpl ext, MixinConfigImpl main, String name, SourceSet sourceSet) {
		this.ext = ext;
		this.sourceSet = sourceSet;

		var project = this.ext.getProject();
		this.config = project.getObjects().newInstance(MixinSourceSetConfig.class);

		this.getRefMap().convention(name + ".refmap.json");
		this.getDisableTargetValidator().convention(main.getDisableTargetValidator());
		this.getDisableTargetExport().convention(main.getDisableTargetExport());
		this.getDisableOverwriteChecker().convention(main.getDisableOverwriteChecker());
		this.getOverwriteErrorLevel().convention(main.getOverwriteErrorLevel());
		this.getDefaultObfuscationEnv().convention(main.getDefaultObfuscationEnv());
		this.getMappingTypes().convention(main.getMappingTypes());
		this.getTokens().convention(main.getTokens());
		this.getExtraMappings().convention(main.getExtraMappings());
		this.getQuiet().convention(main.getQuiet());
		this.getShowMessageTypes().convention(main.getShowMessageTypes());
		this.getMessages().convention(main.getMessages());

		this.ext.defaultMixinBehavior = false;
		var sourceExt = sourceSet.getExtensions().getExtraProperties();
		var compile = project.getTasks().named(sourceSet.getCompileJavaTaskName(), JavaCompile.class);
		var refMapFile = compile.map(task -> new File(task.getTemporaryDir(), task.getName() + "-refmap.json"));
		var mappingFile = compile.map(task -> new File(task.getTemporaryDir(), task.getName() + "-mappings.tsrg"));
		sourceExt.set("refMapFile", refMapFile);

		// Store this field in a local variable so the config lambda doesn't capture 'this'
		var cfg = this.config;
		compile.configure(task -> {
			var mappings = main.getMappings().flatMap(ConvertMappings::getOutput);
			task.getInputs().files(mappings);
			// These are generated by the AP
			var extra = task.getExtensions().getExtraProperties();
			extra.set("refMapFile", refMapFile);
			extra.set("outTsrgFile", mappingFile);
			extra.set("refMap", MixinSourceSetConfigImpl.this.getRefMap());
			task.getOptions().getCompilerArgumentProviders().add(
				project.getObjects().newInstance(CompilerArgs.class, cfg, mappings, mappingFile, refMapFile)
			);
		});

		// Add our output mappings to the merge task
		main.getGeneratedMappings().configure(task -> task.map(mappingFile));
	}

	// region MixinSourceSetConfig properties, manually implemented to prevent capturing sourceSet object by config cache
	@Override
	public Property<String> getRefMap() {
		return this.config.getRefMap();
	}
	@Override
	public Property<Boolean> getDisableTargetValidator() {
		return this.config.getDisableTargetValidator();
	}
	@Override
	public Property<Boolean> getDisableTargetExport() {
		return this.config.getDisableTargetExport();
	}
	@Override
	public Property<Boolean> getDisableOverwriteChecker() {
		return this.config.getDisableOverwriteChecker();
	}
	@Override
	public Property<String> getOverwriteErrorLevel() {
		return this.config.getOverwriteErrorLevel();
	}
	@Override
	public Property<String> getDefaultObfuscationEnv() {
		return this.config.getDefaultObfuscationEnv();
	}
	@Override
	public ListProperty<String> getMappingTypes() {
		return this.config.getMappingTypes();
	}
	@Override
	public MapProperty<String, String> getTokens() {
		return this.config.getTokens();
	}
	@Override
	public ConfigurableFileCollection getExtraMappings() {
		return this.config.getExtraMappings();
	}
	@Override
	public Property<Boolean> getQuiet() {
		return this.config.getQuiet();
	}
	@Override
	public Property<Boolean> getShowMessageTypes() {
		return this.config.getShowMessageTypes();
	}
	@Override
	public MapProperty<String, String> getMessages() {
		return this.config.getMessages();
	}
	// endregion

	abstract static class CompilerArgs implements CommandLineArgumentProvider {
		private final MixinSourceSetConfig config;
		private final Provider<RegularFile> mappings;
		private final Provider<File> outputMappings;
		private final Provider<File> outputRefMap;

		@Inject
		public CompilerArgs(MixinSourceSetConfig config, Provider<RegularFile> mappings, Provider<File> outputMappings, Provider<File> outputRefMap) {
			this.config = config;
			this.mappings = mappings;
			this.outputMappings = outputMappings;
			this.outputRefMap = outputRefMap;
		}

		@Override
		public Iterable<String> asArguments() {
			var ret = new ArrayList<String>();
			ret.add("-AreobfTsrgFile=" + mappings.get().getAsFile().getAbsolutePath());
			ret.add("-AoutTsrgFile=" + outputMappings.get().getAbsolutePath());
			ret.add("-AoutRefMapFile=" + outputRefMap.get().getAbsolutePath());
			if (config.getDisableTargetValidator().getOrElse(false))
				ret.add("-AdisableTargetValidator=true");
			if (config.getDisableTargetExport().getOrElse(false))
				ret.add("-AdisableTargetExport=true");
			if (config.getDisableOverwriteChecker().getOrElse(false))
				ret.add("-AdisableOverwriteChecker=true");
			if (config.getQuiet().getOrElse(false))
				ret.add("-Aquiet=true");
			if (config.getShowMessageTypes().getOrElse(false))
				ret.add("-DshowMessageTypes=true");
			if (config.getOverwriteErrorLevel().isPresent())
				ret.add("-AoverwriteErrorLevel=" + config.getOverwriteErrorLevel().get().trim());
			if (config.getDefaultObfuscationEnv().isPresent())
				ret.add("-AdefaultObfuscationEnv=" + config.getDefaultObfuscationEnv().getOrElse("searge"));
			var mappingTypes = config.getMappingTypes().getOrElse(List.of());
			if (!mappingTypes.isEmpty())
				ret.add("-AmappingTypes=" + String.join(",", mappingTypes));
			var tokens = config.getTokens().getOrElse(Map.of());
			if (!tokens.isEmpty()) {
				var buf = new StringBuilder();
				buf.append("-Atokens=");
				for (var entry : tokens.entrySet()) {
					if (entry.getKey().indexOf(';') != -1 || entry.getValue().indexOf(';') != -1)
						throw new IllegalArgumentException("Invalid token: " + entry.getKey() + '=' + entry.getValue());
					buf.append(entry.getKey()).append('=').append(entry.getValue()).append(';');
				}
				ret.add(buf.toString());
			}
			var extraMappings = config.getExtraMappings().getFiles();
			if (!extraMappings.isEmpty()) {
				var buf = new StringBuilder();
				buf.append("-AreobfTsrgFiles=");
				for (var file : extraMappings)
					buf.append(file.getAbsolutePath()).append(';');
				ret.add(buf.toString());
			}
			var messages = config.getMessages().getOrElse(Map.of());
			if (!messages.isEmpty()) {
				var keyPattern = Pattern.compile("^[A-Z]+[A-Z]_+$");
				var valuePattern = Pattern.compile("^(note|warning|error|disabled)$");
				for (var entry : messages.entrySet()) {
					if (!keyPattern.matcher(entry.getKey()).matches() || !valuePattern.matcher(entry.getValue()).matches())
						throw new IllegalArgumentException("Invalid message config: " + entry.getKey() + '=' + entry.getValue());
					ret.add("-AMSG_" + entry.getKey() + '=' + entry.getValue());
				}
			}

			LOGGER.info("[Renamer][Mixin] Compile Args: " + ret);

			return ret;
		}
	}
}
